services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception-net
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress
      - adminer

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/html
    restart: always
    expose:
      - "9000"
    networks:
      - inception-net
      - redis-net
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      - mariadb
      - redis

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception-net

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    restart: always
    networks:
      - redis-net

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    restart: always
    expose:
      - "9000"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception-net
    depends_on:
      - mariadb

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    volumes:
      - wp_data:/var/www/html
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    restart: always
    secrets:
      - ftp_user
      - ftp_password
    depends_on:
      - wordpress

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt
  ftp_user:
    file: ./secrets/ftp_user.txt
  ftp_password:
    file: ./secrets/ftp_password.txt

networks:
  inception-net:
    driver: bridge
  redis-net:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/db_data
  wp_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/wp_data