services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements
      dockerfile: ./nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception-net
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress
      - adminer
      - portainer
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 443 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/html
    restart: always
    expose:
      - "9000"
    networks:
      - inception-net
      - redis-net
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9000"]
      interval: 45s
      timeout: 5s
      retries: 25
      start_period: 300s

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - inception-net
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    restart: always
    networks:
      - redis-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    restart: always
    expose:
      - "9000"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception-net
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    volumes:
      - wp_data:/var/www/html
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    restart: always
    networks:
      - inception-net
    env_file:
      - .env
    depends_on:
      - wordpress
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 21 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  portainer:
    container_name: portainer
    build: ./requirements/bonus/portainer
    ports:
      - "9443:9443"
    volumes:
      - port_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
        - PORTAINER_ADMIN_PASSWORD=${PORTAINER_ADMIN_PASSWORD}
    restart: always
    networks:
      - inception-net


networks:
  inception-net:
    driver: bridge
  redis-net:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/db_data
  wp_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/wp_data
  port_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/port_data