services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception-net
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/html
    restart: always
    expose:
      - "9000"
    networks:
      - inception-net
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception-net

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt

networks:
  inception-net:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/db_data
  wp_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/wp_data