services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "8080:80"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception-net
    restart: always
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/html
    restart: always
    expose:
      - "9000"
    networks:
      - inception-net
    env_file:
      - .env
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - inception-net

networks:
  inception-net:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/db_data'
  wp_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/wp_data'