services:
  nginx:
    container_name: nginx
    build:
      context: ./containers/nginx
    ports:
      - "443:443"
    volumes:
      - /home/fdi-cecc/data/wordpress:/var/www/html
    networks:
      - inception-net
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context: ./containers/wordpress
    volumes:
      - /home/fdi-cecc/data/wordpress:/var/www/html
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inception-net
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    container_name: mariadb
    build:
      context: ./containers/mariadb
    volumes:
      - /home/fdi-cecc/data/db:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - .env 
    networks:
      - inception-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  inception-net:
    driver: bridge